server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: mycar-service
          uri: lb://MYCAR-SERVICE
          predicates:
            - Path=/mycar/**
          filters:
            - StripPrefix=1
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
