server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://ep-floral-math-ahvyc704-pooler.c-3.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
    username: neondb_owner
    password: npg_rF6gLTwRd5Va
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
