spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@clientedb_high?TNS_ADMIN=${WALLET_DIR}
    username: ADMIN
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.OracleDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8082
