spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082

spring:
  application:
    name: cliente-service
  config:
    import: optional:configserver:https://config-server-bph7.onrender.com

eureka:
  client:
    service-url:
      defaultZone: https://eureka-server-4ipn.onrender.com/eureka/
    register-with-eureka: true
    fetch-registry: true
